2025-04-20 23:23:00 [INFO] app (main.py:11): Starting application…
2025-04-20 23:23:15 [INFO] app (api.py:78): Deleted history for user with id 0
2025-04-20 23:23:35 [INFO] app (api.py:78): Deleted history for user with id 0
2025-04-20 23:24:01 [ERROR] app (api.py:96): HTTPException: History not found
2025-04-20 23:24:30 [INFO] app (api.py:39): user with id 0 sent message: Как ты?
2025-04-20 23:24:35 [INFO] app (api.py:92): Retrieved history for user with id 0
2025-04-20 23:24:57 [INFO] app (api.py:54): user with id 0, have one message on Redis
2025-04-20 23:25:56 [INFO] app (api.py:92): Retrieved history for user with id 0
2025-04-20 23:26:18 [INFO] app (api.py:39): user with id 0 sent message: Как сменить тариф?
2025-04-20 23:26:26 [INFO] app (api.py:92): Retrieved history for user with id 0
2025-04-20 23:26:38 [INFO] app (api.py:61): user with id 0, INTERN NOT SAME: plan_change, greeting
2025-04-20 23:27:04 [INFO] app (api.py:92): Retrieved history for user with id 0
2025-04-20 23:31:04 [INFO] app (api.py:39): user with id 0 sent message: Как заменить тариф?
2025-04-20 23:31:08 [INFO] app (api.py:92): Retrieved history for user with id 0
2025-04-20 23:31:13 [INFO] app (api.py:66): user with id 0, INTERN ARE SAME: plan_change, plan_change
2025-04-21 00:21:35 [INFO] app (main.py:11): Starting application…
2025-04-21 00:21:39 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:51:53 [INFO] app (main.py:11): Starting application…
2025-04-21 01:51:54 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:52:07 [INFO] app (main.py:11): Starting application…
2025-04-21 01:52:14 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:52:24 [INFO] app (main.py:11): Starting application…
2025-04-21 01:53:33 [DEBUG] app (main.py:15): Ping received
2025-04-21 01:53:42 [INFO] app (api.py:94): Retrieved history for user with id 0
2025-04-21 01:53:47 [INFO] app (api.py:80): Deleted history for user with id 0
2025-04-21 01:55:28 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:29 [INFO] app (main.py:11): Starting application…
2025-04-21 01:55:32 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:32 [INFO] app (main.py:11): Starting application…
2025-04-21 01:55:39 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:39 [INFO] app (main.py:11): Starting application…
2025-04-21 01:55:42 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:42 [INFO] app (main.py:11): Starting application…
2025-04-21 01:55:45 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:46 [INFO] app (main.py:11): Starting application…
2025-04-21 01:55:49 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:52 [INFO] app (main.py:11): Starting application…
2025-04-21 01:55:56 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:56 [INFO] app (main.py:11): Starting application…
2025-04-21 01:55:58 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:55:58 [INFO] app (main.py:11): Starting application…
2025-04-21 01:56:03 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:56:03 [INFO] app (main.py:11): Starting application…
2025-04-21 01:56:04 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:56:57 [INFO] app (main.py:11): Starting application…
2025-04-21 01:57:01 [INFO] app (api.py:81): History for user with id 0 deleted successfully
2025-04-21 01:57:04 [INFO] app (api.py:81): History for user with id 0 deleted successfully
2025-04-21 01:57:08 [INFO] app (api.py:81): History for user with id 0 deleted successfully
2025-04-21 01:57:13 [ERROR] app (api.py:102): HTTPException: History not found
2025-04-21 01:57:18 [INFO] app (api.py:40): user with id 0 sent message: Как заменить тариф?
2025-04-21 01:57:18 [ERROR] app (logic.py:43): Error in prepprocess: 'int' object has no attribute 'user_id'
2025-04-21 01:57:18 [ERROR] app (api.py:46): HTTPException: Internal Server Error
2025-04-21 01:58:26 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:58:26 [INFO] app (main.py:11): Starting application…
2025-04-21 01:58:31 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:58:32 [INFO] app (main.py:11): Starting application…
2025-04-21 01:58:37 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:58:38 [INFO] app (main.py:11): Starting application…
2025-04-21 01:58:43 [INFO] app (main.py:20): Shutting down application…
2025-04-21 01:58:43 [INFO] app (main.py:11): Starting application…
2025-04-21 01:58:49 [INFO] app (api.py:40): user with id 0 sent message: Как заменить тариф?
2025-04-21 01:58:49 [ERROR] app (logic.py:43): Error in prepprocess: Error: 422
2025-04-21 01:58:49 [ERROR] app (api.py:47): HTTPException: Internal Server Error
2025-04-21 02:00:37 [INFO] app (main.py:20): Shutting down application…
2025-04-21 02:00:37 [INFO] app (main.py:11): Starting application…
2025-04-21 02:00:41 [INFO] app (api.py:40): user with id 0 sent message: Как заменить тариф?
2025-04-21 02:07:02 [INFO] app (main.py:11): Starting application…
2025-04-21 02:08:30 [INFO] app (api.py:82): History for user with id 0 deleted successfully
2025-04-21 02:08:37 [ERROR] app (api.py:103): HTTPException: History not found
2025-04-21 02:08:45 [INFO] app (api.py:40): user with id 0 sent message: string
2025-04-21 02:11:22 [INFO] app (main.py:11): Starting application…
2025-04-21 02:11:24 [INFO] app (api.py:57): user with id 0, have one message on Redis
2025-04-21 02:13:33 [INFO] app (main.py:20): Shutting down application…
2025-04-21 02:13:35 [INFO] app (main.py:11): Starting application…
2025-04-21 02:13:54 [INFO] app (main.py:20): Shutting down application…
2025-04-21 02:13:54 [INFO] app (main.py:11): Starting application…
2025-04-21 02:14:04 [INFO] app (main.py:20): Shutting down application…
2025-04-21 02:14:09 [INFO] app (main.py:11): Starting application…
2025-04-21 02:14:19 [INFO] app (api.py:99): Retrieved history for user with id 0
2025-04-21 02:14:24 [INFO] app (api.py:82): History for user with id 0 deleted successfully
2025-04-21 02:14:30 [INFO] app (api.py:40): user with id 0 sent message: string
2025-04-21 02:18:05 [INFO] app (main.py:11): Starting application…
2025-04-21 02:18:10 [INFO] app (api.py:82): History for user with id 0 deleted successfully
2025-04-21 02:18:14 [INFO] app (api.py:40): user with id 0 sent message: string
2025-04-21 02:18:15 [INFO] app (api.py:57): user with id 0, have one message on Redis
2025-04-21 02:19:03 [INFO] app (api.py:40): user with id 0 sent message: string
2025-04-21 02:19:04 [INFO] app (api.py:69): user with id 0, INTERN ARE SAME: information_request, information_request
2025-04-21 02:19:14 [INFO] app (api.py:82): History for user with id 0 deleted successfully
2025-04-21 02:19:18 [INFO] app (main.py:20): Shutting down application…
2025-04-21 03:49:20 [INFO] app (main.py:11): Starting application…
2025-04-21 03:49:37 [ERROR] app (api.py:103): HTTPException: History not found
2025-04-21 03:49:43 [INFO] app (api.py:40): user with id 0 sent message: string
2025-04-21 03:49:43 [ERROR] app (api.py:47): HTTPException: Preprocess service error: Cannot connect to host localhost:8003 ssl:False [Multiple exceptions: [Errno 61] Connect call failed ('::1', 8003, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8003)]
2025-04-21 03:49:57 [INFO] app (api.py:40): user with id 0 sent message: string
2025-04-21 03:49:58 [INFO] app (api.py:64): user with id 0, INTERN NOT SAME: information_request, None
2025-04-21 03:50:04 [INFO] app (api.py:99): Retrieved history for user with id 0
2025-04-21 03:53:05 [INFO] app (main.py:20): Shutting down application…
2025-04-21 03:58:35 [INFO] app (main.py:11): Starting application…
2025-04-21 03:58:46 [INFO] app (main.py:20): Shutting down application…
2025-04-21 03:58:46 [INFO] app (main.py:11): Starting application…
2025-04-21 03:58:53 [INFO] app (main.py:20): Shutting down application…
2025-04-21 03:59:31 [INFO] app (main.py:11): Starting application…
2025-04-21 03:59:51 [INFO] app (api.py:113): Retrieved history for user with id 0
2025-04-21 04:00:46 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:00:46 [INFO] app (main.py:11): Starting application…
2025-04-21 04:00:54 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:00:54 [INFO] app (main.py:11): Starting application…
2025-04-21 04:01:03 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:01:04 [INFO] app (main.py:11): Starting application…
2025-04-21 04:03:43 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:03:44 [INFO] app (main.py:11): Starting application…
2025-04-21 04:04:07 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:05:10 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:05:10 [INFO] app (main.py:11): Starting application…
2025-04-21 04:05:14 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:05:15 [INFO] app (main.py:11): Starting application…
2025-04-21 04:05:36 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:06:57 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:06:59 [INFO] app (main.py:11): Starting application…
2025-04-21 04:07:00 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:08:16 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:08:17 [INFO] app (main.py:11): Starting application…
2025-04-21 04:08:20 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:08:21 [INFO] app (main.py:11): Starting application…
2025-04-21 04:08:21 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:08:38 [ERROR] app (api.py:117): HTTPException: History not found
2025-04-21 04:08:44 [INFO] app (api.py:127): Knowledge for user with id 0 deleted successfully
2025-04-21 04:08:51 [ERROR] app (api.py:117): HTTPException: History not found
2025-04-21 04:08:52 [ERROR] app (api.py:117): HTTPException: History not found
2025-04-21 04:09:03 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:12:00 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:12:09 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:12:29 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:15:54 [INFO] app (api.py:127): Knowledge for user with id 0 deleted successfully
2025-04-21 04:15:58 [ERROR] app (api.py:117): HTTPException: History not found
2025-04-21 04:16:12 [INFO] app (api.py:127): Knowledge for user with id 0 deleted successfully
2025-04-21 04:16:17 [ERROR] app (api.py:117): HTTPException: History not found
2025-04-21 04:16:25 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:17:44 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:17:46 [INFO] app (main.py:11): Starting application…
2025-04-21 04:17:48 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:25:32 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:26:00 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:26:00 [INFO] app (main.py:11): Starting application…
2025-04-21 04:26:07 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:26:59 [INFO] app (api.py:113): Retrieved history knowledge for user with id 0
2025-04-21 04:27:10 [INFO] app (api.py:127): Knowledge for user with id 0 deleted successfully
2025-04-21 04:27:14 [ERROR] app (api.py:117): HTTPException: History not found
2025-04-21 04:30:14 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:14 [INFO] app (main.py:11): Starting application…
2025-04-21 04:30:16 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:17 [INFO] app (main.py:11): Starting application…
2025-04-21 04:30:28 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:29 [INFO] app (main.py:11): Starting application…
2025-04-21 04:30:42 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:42 [INFO] app (main.py:11): Starting application…
2025-04-21 04:30:43 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:44 [INFO] app (main.py:11): Starting application…
2025-04-21 04:30:50 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:50 [INFO] app (main.py:11): Starting application…
2025-04-21 04:30:54 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:54 [INFO] app (main.py:11): Starting application…
2025-04-21 04:30:55 [INFO] app (main.py:20): Shutting down application…
2025-04-21 04:30:56 [INFO] app (main.py:11): Starting application…
2025-04-21 04:31:36 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:24:15 [INFO] app (main.py:11): Starting application…
2025-04-21 05:24:51 [WARNING] app (logic.py:27): Call_eis - promlem:{e}
2025-04-21 05:26:00 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:01 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:02 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:02 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:04 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:04 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:07 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:07 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:18 [WARNING] app (logic.py:27): Call_eis - promlem:{e}
2025-04-21 05:26:40 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:41 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:44 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:44 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:49 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:49 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:54 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:54 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:57 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:57 [INFO] app (main.py:11): Starting application…
2025-04-21 05:26:58 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:26:59 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:01 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:01 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:07 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:08 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:10 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:11 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:17 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:18 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:21 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:21 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:26 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:26 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:29 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:30 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:42 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:43 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:44 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:45 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:49 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:50 [INFO] app (main.py:11): Starting application…
2025-04-21 05:27:52 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:27:52 [INFO] app (main.py:11): Starting application…
2025-04-21 05:28:07 [WARNING] app (logic.py:27): Call_eis - promlem:{e}
2025-04-21 05:28:07 [ERROR] app (api.py:41): HTTPException: Not found message in history
2025-04-21 05:28:51 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:28:51 [INFO] app (main.py:11): Starting application…
2025-04-21 05:28:53 [WARNING] app (logic.py:27): Call_eis - promlem:Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
2025-04-21 05:28:53 [ERROR] app (api.py:41): HTTPException: Not found message in history
2025-04-21 05:29:22 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:29:22 [INFO] app (main.py:11): Starting application…
2025-04-21 05:29:25 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:29:25 [INFO] app (main.py:11): Starting application…
2025-04-21 05:29:27 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:29:27 [INFO] app (main.py:11): Starting application…
2025-04-21 05:29:29 [WARNING] app (logic.py:27): Call_eis - promlem:422 Client Error: Unprocessable Content for url: http://localhost:8003/api/eia-agent/analyze
2025-04-21 05:29:29 [ERROR] app (api.py:41): HTTPException: Not found message in history
2025-04-21 05:30:35 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:30:35 [INFO] app (main.py:11): Starting application…
2025-04-21 05:30:39 [INFO] app (logic.py:51): user with id 0, INTERN NOT SAME: information_request, None
2025-04-21 05:31:30 [INFO] app (api.py:76): History for user with id 0 deleted successfully
2025-04-21 05:31:38 [WARNING] app (logic.py:27): Call_eis - promlem:500 Server Error: Internal Server Error for url: http://localhost:8003/api/eia-agent/analyze
2025-04-21 05:31:38 [ERROR] app (api.py:41): HTTPException: Not found message in history
2025-04-21 05:33:45 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:33:50 [INFO] app (main.py:11): Starting application…
2025-04-21 05:33:58 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:33:59 [INFO] app (main.py:11): Starting application…
2025-04-21 05:34:08 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:34:09 [INFO] app (main.py:11): Starting application…
2025-04-21 05:34:10 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:34:11 [INFO] app (main.py:11): Starting application…
2025-04-21 05:34:18 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:34:19 [INFO] app (main.py:11): Starting application…
2025-04-21 05:34:25 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:34:25 [INFO] app (main.py:11): Starting application…
2025-04-21 05:34:29 [INFO] app (api.py:42): user with id 0 sent message: как дела?
2025-04-21 05:34:30 [INFO] app (logic.py:40): user with id 0, have one message on Redis
2025-04-21 05:35:34 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:35:35 [INFO] app (main.py:11): Starting application…
2025-04-21 05:35:36 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:35:36 [INFO] app (main.py:11): Starting application…
2025-04-21 05:35:37 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:35:38 [INFO] app (main.py:11): Starting application…
2025-04-21 05:35:50 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:35:50 [INFO] app (main.py:11): Starting application…
2025-04-21 05:35:57 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:35:58 [INFO] app (main.py:11): Starting application…
2025-04-21 05:36:02 [INFO] app (api.py:42): user with id 0 sent message: как дела?
2025-04-21 05:36:03 [INFO] app (logic.py:54): user with id 0, INTERN ARE SAME: greeting, greeting
2025-04-21 05:36:35 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:36:35 [INFO] app (main.py:11): Starting application…
2025-04-21 05:36:37 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:36:37 [INFO] app (main.py:11): Starting application…
2025-04-21 05:36:39 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:36:40 [INFO] app (main.py:11): Starting application…
2025-04-21 05:36:44 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:36:44 [INFO] app (main.py:11): Starting application…
2025-04-21 05:36:45 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:36:46 [INFO] app (main.py:11): Starting application…
2025-04-21 05:36:49 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:36:49 [INFO] app (main.py:11): Starting application…
2025-04-21 05:37:14 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:37:14 [INFO] app (main.py:11): Starting application…
2025-04-21 05:37:17 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:37:18 [INFO] app (main.py:11): Starting application…
2025-04-21 05:37:20 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:37:27 [INFO] app (main.py:11): Starting application…
2025-04-21 05:37:31 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:37:35 [INFO] app (main.py:11): Starting application…
2025-04-21 05:37:37 [INFO] app (api.py:42): user with id 0 sent message: как дела?
2025-04-21 05:37:37 [INFO] app (logic.py:23): call EIA
2025-04-21 05:37:38 [INFO] app (logic.py:56): user with id 0, INTERN ARE SAME: greeting, greeting
2025-04-21 05:37:59 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:38:01 [INFO] app (main.py:11): Starting application…
2025-04-21 05:38:01 [INFO] app (api.py:42): user with id 0 sent message: как дела?
2025-04-21 05:38:01 [INFO] app (logic.py:23): call EIA
2025-04-21 05:38:02 [INFO] app (logic.py:56): user with id 0, INTERN ARE SAME: greeting, greeting
2025-04-21 05:38:27 [INFO] app (main.py:20): Shutting down application…
2025-04-21 05:38:27 [INFO] app (main.py:11): Starting application…
2025-04-21 05:38:41 [INFO] app (api.py:98): Retrieved history for user with id 0
2025-04-21 05:39:01 [INFO] app (api.py:98): Retrieved history for user with id 0
2025-04-21 05:39:07 [INFO] app (api.py:112): Retrieved history knowledge for user with id 0
2025-04-21 05:41:13 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:20:27 [INFO] app (main.py:11): Starting application…
2025-04-21 06:20:37 [INFO] app (api.py:126): Knowledge for user with id 0 deleted successfully
2025-04-21 06:20:42 [ERROR] app (api.py:116): HTTPException: History not found
2025-04-21 06:20:49 [INFO] app (api.py:42): user with id 0 sent message: как дела?
2025-04-21 06:20:49 [INFO] app (logic.py:23): call EIA
2025-04-21 06:20:49 [WARNING] app (logic.py:29): Call_eis - promlem:HTTPConnectionPool(host='localhost', port=8003): Max retries exceeded with url: /api/eia-agent/analyze (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105247b60>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-04-21 06:20:49 [ERROR] app (api.py:46): HTTPException: Not found message in history
2025-04-21 06:21:32 [INFO] app (api.py:42): user with id 0 sent message: как дела?
2025-04-21 06:21:32 [INFO] app (logic.py:23): call EIA
2025-04-21 06:21:33 [INFO] app (logic.py:53): user with id 0, INTERN NOT SAME: greeting, None
2025-04-21 06:21:33 [INFO] app (logic.py:12): call RAG
2025-04-21 06:21:45 [INFO] app (api.py:98): Retrieved history for user with id 0
2025-04-21 06:22:00 [INFO] app (api.py:81): History for user with id 0 deleted successfully
2025-04-21 06:22:08 [ERROR] app (api.py:102): HTTPException: History not found
2025-04-21 06:22:12 [INFO] app (api.py:112): Retrieved history knowledge for user with id 0
2025-04-21 06:22:18 [INFO] app (api.py:126): Knowledge for user with id 0 deleted successfully
2025-04-21 06:22:43 [INFO] app (api.py:42): user with id 0 sent message: Здравствуйте как пополнить баланс?
2025-04-21 06:22:43 [INFO] app (logic.py:23): call EIA
2025-04-21 06:22:44 [INFO] app (logic.py:42): user with id 0, have one message on Redis
2025-04-21 06:22:44 [INFO] app (logic.py:12): call RAG
2025-04-21 06:30:19 [INFO] app (api.py:112): Retrieved history knowledge for user with id 0
2025-04-21 06:30:23 [INFO] app (api.py:98): Retrieved history for user with id 0
2025-04-21 06:32:14 [INFO] app (api.py:42): user with id 0 sent message: Здравствуйте как подключить интернет?
2025-04-21 06:32:14 [INFO] app (logic.py:23): call EIA
2025-04-21 06:32:14 [INFO] app (logic.py:53): user with id 0, INTERN NOT SAME: service_connection, billing
2025-04-21 06:32:14 [INFO] app (logic.py:12): call RAG
2025-04-21 06:34:48 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:34:48 [INFO] app (main.py:11): Starting application…
2025-04-21 06:34:57 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:34:57 [INFO] app (main.py:11): Starting application…
2025-04-21 06:35:06 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:35:06 [INFO] app (main.py:11): Starting application…
2025-04-21 06:35:10 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:35:11 [INFO] app (main.py:11): Starting application…
2025-04-21 06:35:18 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:37:20 [INFO] app (main.py:11): Starting application…
2025-04-21 06:37:33 [INFO] app (api.py:56): Retrieved history for user with id 0
2025-04-21 06:40:58 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:40:58 [INFO] app (main.py:11): Starting application…
2025-04-21 06:41:02 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:41:02 [INFO] app (main.py:11): Starting application…
2025-04-21 06:41:03 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:41:04 [INFO] app (main.py:11): Starting application…
2025-04-21 06:41:14 [INFO] app (api.py:56): Retrieved history for user with id 0
2025-04-21 06:43:12 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:43:12 [INFO] app (main.py:11): Starting application…
2025-04-21 06:43:17 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:43:18 [INFO] app (main.py:11): Starting application…
2025-04-21 06:43:37 [INFO] app (api.py:84): Deleted history for user with id 0
2025-04-21 06:44:09 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:44:09 [INFO] app (main.py:11): Starting application…
2025-04-21 06:44:14 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:44:14 [INFO] app (main.py:11): Starting application…
2025-04-21 06:44:19 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:45:46 [INFO] app (main.py:11): Starting application…
2025-04-21 06:45:55 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:45:56 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:06 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:07 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:11 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:11 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:15 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:15 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:25 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:27 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:29 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:33 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:41 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:41 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:45 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:45 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:48 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:48 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:50 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:50 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:54 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:54 [INFO] app (main.py:11): Starting application…
2025-04-21 06:46:56 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:46:56 [INFO] app (main.py:11): Starting application…
2025-04-21 06:47:02 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:47:02 [INFO] app (main.py:11): Starting application…
2025-04-21 06:47:08 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:47:08 [INFO] app (main.py:11): Starting application…
2025-04-21 06:47:23 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:47:27 [INFO] app (main.py:11): Starting application…
2025-04-21 06:47:34 [INFO] app (main.py:20): Shutting down application…
2025-04-21 06:47:35 [INFO] app (main.py:11): Starting application…
2025-04-21 06:48:13 [INFO] app (api.py:42): user with id 0 sent message: Как пополнить баланс?
2025-04-21 06:48:13 [INFO] app (logic.py:23): call EIA
2025-04-21 06:48:13 [INFO] app (logic.py:69): user with id 0, INTERN NOT SAME: billing, service_connection
2025-04-21 06:48:13 [INFO] app (logic.py:12): call RAG
2025-04-21 06:48:14 [INFO] app (logic.py:34): call EIA
2025-04-21 06:48:17 [INFO] app (logic.py:75): call AS - success
2025-04-21 06:48:23 [INFO] app (api.py:84): Deleted history for user with id 0
2025-04-21 06:48:40 [ERROR] app (api.py:60): HTTPException: History not found
2025-04-21 06:48:47 [INFO] app (api.py:42): user with id 0 sent message: Как пополнить баланс?
2025-04-21 06:48:47 [INFO] app (logic.py:23): call EIA
2025-04-21 06:48:47 [INFO] app (logic.py:78): user with id 0, INTERN ARE SAME: billing, billing
2025-04-21 06:48:55 [ERROR] app (api.py:60): HTTPException: History not found
2025-04-21 06:49:04 [INFO] app (api.py:136): Retrieved history for user with id 0
2025-04-21 06:49:12 [INFO] app (api.py:42): user with id 0 sent message: Как пополнить баланс?
2025-04-21 06:49:12 [INFO] app (logic.py:23): call EIA
2025-04-21 06:49:12 [INFO] app (logic.py:78): user with id 0, INTERN ARE SAME: billing, billing
2025-04-21 06:49:17 [INFO] app (api.py:136): Retrieved history for user with id 0
2025-04-21 06:49:26 [INFO] app (api.py:119): History for user with id 0 deleted successfully
2025-04-21 06:49:29 [INFO] app (api.py:42): user with id 0 sent message: Как пополнить баланс?
2025-04-21 06:49:29 [INFO] app (logic.py:23): call EIA
2025-04-21 06:49:30 [INFO] app (logic.py:54): user with id 0, have one message on Redis
2025-04-21 06:49:30 [INFO] app (logic.py:12): call RAG
2025-04-21 06:49:30 [INFO] app (logic.py:34): call EIA
2025-04-21 06:49:36 [INFO] app (logic.py:64): call AS - success
2025-04-21 06:49:40 [INFO] app (api.py:56): Retrieved history for user with id 0
2025-04-21 06:49:56 [INFO] app (api.py:150): Retrieved history knowledge for user with id 0
2025-04-21 06:50:15 [INFO] app (api.py:119): History for user with id 0 deleted successfully
2025-04-21 06:50:22 [INFO] app (api.py:84): Deleted history for user with id 0
2025-04-21 06:50:34 [INFO] app (api.py:164): Knowledge for user with id 0 deleted successfully
2025-04-21 06:50:38 [ERROR] app (api.py:154): HTTPException: History not found
2025-04-21 06:50:41 [ERROR] app (api.py:140): HTTPException: History not found
2025-04-21 06:50:45 [ERROR] app (api.py:60): HTTPException: History not found
2025-04-21 06:50:52 [INFO] app (api.py:42): user with id 0 sent message: Как пополнить баланс?
2025-04-21 06:50:52 [INFO] app (logic.py:23): call EIA
2025-04-21 06:50:52 [INFO] app (logic.py:54): user with id 0, have one message on Redis
2025-04-21 06:50:52 [INFO] app (logic.py:12): call RAG
2025-04-21 06:50:52 [INFO] app (logic.py:34): call EIA
2025-04-21 06:50:56 [INFO] app (logic.py:64): call AS - success
2025-04-21 06:51:03 [INFO] app (api.py:56): Retrieved history for user with id 0
2025-04-21 06:53:36 [INFO] app (api.py:42): user with id 0 sent message: Какой тариф советуете подключить??
2025-04-21 06:53:36 [INFO] app (logic.py:23): call EIA
2025-04-21 06:53:37 [INFO] app (logic.py:69): user with id 0, INTERN NOT SAME: information_request, billing
2025-04-21 06:53:37 [INFO] app (logic.py:12): call RAG
2025-04-21 06:53:37 [INFO] app (logic.py:34): call EIA
2025-04-21 06:53:42 [INFO] app (logic.py:75): call AS - success
2025-04-21 06:53:48 [INFO] app (api.py:56): Retrieved history for user with id 0
2025-04-21 06:57:01 [INFO] app (main.py:20): Shutting down application…
2025-04-21 07:35:00 [INFO] app (main.py:11): Starting application…
2025-04-21 07:38:32 [INFO] app (main.py:20): Shutting down application…
